image: node:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - npm install

stages:
  # - run
  - deploy

# test: 
#   stage: test
#   script:
#     - npm run test

# run:
#   only:
#     - master
#     - ci_cd
#   stage: run
#   script:
#     - npm run serve

deplotToAWS:
  only:
    - master
    # - ci_cd
  stage: deploy
  script:
    - bash deploy/deploy.sh